name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Check Docker and kubectl
      run: |
        docker --version
        kubectl version --client
    
    - name: Build Frontend
      run: |
        cd frontend
        docker build -t frontend:latest .
    
    - name: Build Backend
      run: |
        cd backend
        docker build -t backend:latest .
    
    - name: Deploy to Kubernetes
      if: github.ref == 'refs/heads/main'  # Only deploy on main branch
      run: |
        kubectl apply -f k8s/database.yaml
        kubectl wait --for=condition=ready pod -l app=postgres --timeout=300s
        
        kubectl apply -f k8s/backend.yaml
        kubectl wait --for=condition=ready pod -l app=backend --timeout=300s
        
        kubectl apply -f k8s/frontend.yaml
        kubectl wait --for=condition=ready pod -l app=frontend --timeout=300s
    
    - name: Verify Deployment
      if: github.ref == 'refs/heads/main'
      run: |
        kubectl get pods
        kubectl get services 