name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Frontend
      run: |
        cd frontend
        docker build -t frontend:latest .
    
    - name: Build Backend
      run: |
        cd backend
        docker build -t backend:latest .
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/database.yaml
        kubectl apply -f k8s/backend.yaml
        kubectl apply -f k8s/frontend.yaml 